version: '3.8'

services:
  employee-management-system:
    build: .
    container_name: employee-management-system
    ports:
      - "9090:8080"
    depends_on:
      - graphite

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "8081:80"    # Graphite dashboard
      - "2003:2003"  # Plaintext protocol port
      - "8125:8125/udp"  # StatsD metrics
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - graphite
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
